import streamlit as st
from auth import check_password, logout

st.set_page_config(page_title="Research Lab Admin", page_icon="🔬", layout="wide")

if not check_password():
    st.stop()  # Do not show anything else if authentication fails

# Sidebar
st.sidebar.title("🔬 Research Lab Config")
st.sidebar.success(f"Logged in as {st.session_state.get('username', 'Admin')}")

if st.sidebar.button("Logout"):
    logout()
    st.rerun()

st.sidebar.divider()
st.sidebar.markdown("### 🛡️ Data Backup")
if st.sidebar.button("Download Full Backup"):
    import shutil
    import datetime
    import os
    
    # Create zip
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_filename = f"lab_backup_{timestamp}"
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(root_dir, "data")
    
    shutil.make_archive(backup_filename, 'zip', data_dir)
    
    with open(f"{backup_filename}.zip", "rb") as f:
        st.sidebar.download_button(
            label="⬇️ Click to Save Zip",
            data=f,
            file_name=f"{backup_filename}.zip",
            mime="application/zip"
        )
    st.sidebar.success("Backup Ready!")

# --- Newsletter Generator ---
st.sidebar.divider()
if st.sidebar.button("📰 Generate Newsletter"):
    st.sidebar.info("Generating summary...")
    from data_manager import DataLayer
    db = DataLayer()
    
    # Get recent data
    pubs = db.get_publications()
    news = db.get_news()
    projects = db.get_projects()
    
    # Mock logic for "recent"
    current_year = 2024
    recent_pubs = [p for p in pubs if p.year == current_year]
    recent_news = [n for n in news if n.publish_date.startswith(str(current_year))]
    
    summary = f"""# 📢 SK Lab Quarterly Update ({current_year})

## 🔬 Research Highlights
We are excited to share our latest progress:
"""
    for p in recent_pubs[:3]:
        summary += f"- **{p.title}** ({p.venue})\n"
        
    summary += "\n## 📰 Lab News\n"
    for n in recent_news[:3]:
        summary += f"- {n.title} ({n.publish_date})\n"
        
    summary += "\n## 🚀 Active Projects\n"
    active_projs = [p for p in projects if p.status == "Ongoing"]
    for p in active_projs[:3]:
        summary += f"- {p.title}\n"
        
    summary += "\n---\n*Generated by SK Lab Admin*"
    
    with st.expander("📝 Generated Draft (Copy this)", expanded=True):
        st.code(summary, language="markdown")

from data_manager import DataLayer

st.title("Admin Dashboard")

db = DataLayer()
people = db.get_people()
projects = db.get_projects()
pubs = db.get_publications()
news = db.get_news()

# --- TABS ---
tab_dash, tab_guide = st.tabs(["📊 Dashboard", "ℹ️ Info & Guide"])

# --- DASHBOARD TAB ---
with tab_dash:
    # Stats Row
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total People", len(people))
    c2.metric("Active Projects", len([p for p in projects if p.status == "Ongoing"]))
    c3.metric("Publications", len(pubs))
    c4.metric("News Posts", len(news))

    st.divider()

    # Recent Activity / Quick Links
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("Latest News")
        if news:
            sorted_news = sorted(news, key=lambda n: n.publish_date, reverse=True)[:5]
            for n in sorted_news:
                st.info(f"[{n.publish_date}] {n.title}")
        else:
            st.write("No news yet.")

    with col2:
        st.subheader("Quick Actions")
        st.markdown("""
        - [Manage People](/People)
        - [Update Projects](/Projects)
        - [Add Publication](/Publications)
        """)

    st.divider()

    st.subheader("🕵️ Audit Log")
    logs = db.get_audit_logs()
    if not logs:
        st.info("No actions recorded yet.")
    else:
        # Simple table
        st.dataframe(logs, use_container_width=True)

# --- GUIDE TAB ---
with tab_guide:
    st.markdown("""
    # 📘 Admin User Manual
    Welcome to the SK Lab Control Center. This dashboard allows you to manage every aspect of your research website.

    ---
    
    ### 🏗️ **Core Concept: The "Rebuild" Button**
    The website is **Static**. This means it is ultra-fast and secure, but it doesn't update instantly when you change data.
    *   **Concept**: You make changes in this Admin Panel -> Save them -> **Rebuild**.
    *   **How-To**: Go to **Settings** (`9_Settings`) and click **"♻️ Rebuild Website"**.
    *   **When**: Do this after you have finished a batch of edits (e.g., added 5 new papers).

    ---

    ### 👥 **Page: People**
    Manage your team members.
    *   **Add New**: Use the "Add New" tab. Note the **"Role"** field filters members on the "People" page (PI, PhD, etc.).
    *   **Draft Mode**: Toggle **"Published"** to OFF to hide someone (e.g., a new joiner who hasn't started).
    *   **Bulk Edit**: Switch to the **"Bulk Edit"** tab to view your team as an Excel sheet. Great for fixing years or titles quickly.
    *   **Alumni**: Mark role as "Alumni" to move them to the alumni section automatically.

    ---

    ### 📚 **Page: Publications**
    Your research impact.
    *   **Smart Import**: DO NOT type manually! Go to **"Smart Import"** tab.
        *   **DOI**: Paste a DOI -> Fetch Metadata -> Import.
        *   **BibTeX**: Upload a `.bib` file to import 100s of papers at once.
    *   **Promote to News**: On any paper card, click **"📢 Promote to News"**. It auto-writes a "New Paper Published" news post for you.
    *   **PDFs/DOIs**: Always add links. The Broken Link Checker will warn you if they die.

    ---

    ### 🚀 **Page: Projects**
    Showcase your work.
    *   **Images**: You can upload multiple images.
    *   **Visual Manager**: Review uploaded images in a grid and delete old ones.
    *   **Status**: Mark as "Ongoing" or "Completed". Ongoing projects appear on the Home page summary.

    ---

    ### 🖼️ **Page: Media Library**
    Disk space management.
    *   **Orphaned Files**: Images that you uploaded but deleted the Person/Project later.
    *   **Cleanup**: Click **"🗑️ Delete Orphaned Files"** to keep your server clean.

    ---

    ### 🎨 **Page: Settings**
    The control room.
    *   **Theme Customizer**: Change the website's brand colors without code.
    *   **Health Check**: Click "Run Health Check" to scan every link in your database for 404 errors.
    *   **Disaster Recovery**:
        1.  **Backup**: Click "Download Full Backup" in the **Sidebar** to get a `.zip` of all your data.
        2.  **Restore**: Upload that `.zip` in Settings to revert the lab to that state.
    *   **Password**: Change your admin login credentials here.

    ---

    ### ❓ **FAQ**
    *   **Q: I saved a person but they aren't on the website?**
        *   A: Did you click **"♻️ Rebuild Website"** in Settings?
    *   **Q: Where do images go?**
        *   A: `/web/public/uploads`. The Media Library manages this folder.
    *   **Q: Can I edit the text on the Home Page?**
        *   A: Yes, go to **Lab Info** (`2_Lab_Info`). You can also edit SEO metadata there.
    """)
